blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/bunworks/bun-turbo-starter/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://github.com/bunworks/bun-turbo-starter/blob/main/README.md
    about: Check the documentation for help
